### ISSUE TITLE
How to upload files using Meteor.DDP to FS collection

### ISSUE THREAD

**Issue by dhobla007** [sgaluza/Meteor.DDP#5]
Hi,

I am trying to find way to upload files using Meteor.DDP to FS collection.
Please let me know if there is any way doing this from .net client.
Don't want to store Base64 string to MongoDB, instead want to save as file to FS collection.

Any Quick help is appreciated.

Thanks in advance,
Sanjay Jha

**Comment by sgaluza** [comment]
Hi, Sanjay

I believe base64 is the only option for now, because DDP relies on standard websockets approach.

**Comment by dhobla007** [comment]
Hi sgaluza,

Is there any option of saving base64 content to file at server in meteor?

**Comment by sgaluza** [comment]
I think that you can use CFS or standard 'fs' module via Npm.require, however it is not related to DDP:)

**Comment by Type1J** [comment]
@dhobla007 See https://github.com/CollectionFS/Meteor-CollectionFS/blob/master/packages/upload-http/upload-http-client.js

You may have to dig a bit. Basically, you add an entry to the Mongo collection to represent the file, then upload the file to a url based on that entry's _id... I think.

I hope that helps.

**Comment by Type1J** [comment]
By the way, although you typically let CFS know that the file is coming through DDP (using an insert relayed to the server, or using a Meteor method, which does the insert on the server side), you upload the file using HTTP, not DDP.
