### ISSUE TITLE
Subscription not returning collection

### ISSUE THREAD

**Issue by MarceloPrado** [sgaluza/Meteor.DDP#8]
Hi, good afternoon!

I'm trying to return a Meteor Collection to a C# console application. Following the docs, I was able to implement Meteor.DDP to publish information to Meteor Server. But my problem resides on the subscription. My server detects that a subscription call was made, but my C# app doesn't return anything from it. 

**Here's the code of my Meteor publication**
```
Meteor.publish('MeteorPublished', () => {
  console.log('publication called');
  return Clients.find({});
});
```

**Heres the Meteor.DDP C# code**
```
public class ServerComunication
{

	private static DdpClient client;


	public static void ConnectToServer()
	{
		client = new DdpClient("localhost:3000");
		client.ConnectAsync().Wait();
		Subscribe();
		ReturnComanda();

		// Subscribe or publish then...
	}

	private static void Subscribe()
	{
		client.Message += OnMessage;
		client.Subscribe(Guid.NewGuid().ToString("N"), "MeteorPublished");
	}

	private static void OnMessage(object sender, DdpMessageEventArgs e)
	{
		Console.WriteLine("Message from Meteor! Item {0}::{1}:  {2}\n{3}", e.Collection, e.Id, e.Method, e.Data);
	}

	private static void ReturnComanda()
	{

		client.Publish(Guid.NewGuid().ToString("N"), "MeteorMethod", new
		{
			hello = "hello",
			data = "Hello, Meteor!!!"
		});
	}
}
```

When I run the app, Meteor server logs `publication called`. But C# console doesn't log anything.
Am I missing something?

PS: the Publish function works just fine

Thanks,
Marcelo

**Comment by manuelro** [comment]
I'm no C# expert but have thought about implementing the MVVM pattern to get notified when data arrives? Meteor's DDP is async, therefore you will not see anything at first, the data will get to you eventually.
